os: linux
language: node_js
node_js: "10.16.3"

end:
  - NODE_ENV=TEST

before_script:
  - pwd
  - EXPORT VERSION=$TRAVIS_BUILD_NUMBER
  - echo will build sonnht1409/price-bid:$VERSION
after_script:
  - tree

branches:
  only:
    - master

cache:
  npm: false
  yarn: false
  directories:
    - node_modules

sudo: false

services:
  - docker
script:
  - docker run build -t sonnht1409/price-bid:$VERSION -f dockerfile .
