os: linux
language: node_js
node_js: "10.16.3"

env:
  - NODE_ENV=TEST
  - VERSION=$TRAVIS_BUILD_NUMBER
before_script:
  - pwd
  - echo will build sonnht1409/price-bid:$TRAVIS_BUILD_NUMBER
after_script:
  - tree

branches:
  only:
    - master

cache:
  npm: false
  yarn: false
  directories:
    - node_modules

services:
  - docker
install:
  - docker run build -t sonnht1409/price-bid:$VERSION .
