os: linux
language: node_js
node_js: "10.17"

before_install:
  - pwd
  - echo $TRAVIS_BUILD_NUMBER
after_script:
  - echo $TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER

branches:
  only:
    - master

cache:
  npm: false
  yarn: false

services:
  - docker
install:
  - npm ci
  - docker build -t sonnht1409/price-bid:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER .
