os: linux
language: node_js
node_js: "10.16.3"

end:
  - NODE_ENV=TEST

before_script:
  - pwd
  - echo will build bid-price/$TRAVIS_BUILD_NUMBER
after_script:
  - tree

branches:
  only:
    - master

cache:
  npm: false
  yarn: false
  directories:
    - node_modules

sudo: false

services:
  - docker
script:
  - docker run build -t bid-price/$TRAVIS_BUILD_NUMBER -f dockerfile .
